### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by J0ker98** [Mirreski/RandomSK#19]
Each time I restart my server and it loads RandomSK (2.0 Final Beta) I get the following error: http://pastebin.com/RgLLaspD

How can this be fixed?

**Comment by Mirreski** [comment]
It is because SkQuery4 registers a classinfo with the same name.

**If you want the Statistics features to work.**
1. Open up SkQuery4 in Winrar. Not SkQuery3.
2. Go to net/skquery/util/minecraft
3. Delete the StatisticData.class and StatisticData$1.class
4. Restart the server with the now edited SkQuery 4. Should work now.

**If you don't need to have statistics working or the above didn't work. Or you are using 1.8 spigot/bukkit.**

Open up RandomSK in winrar.
Go to me/mirreski/random/skript/features/classinfo
Delete the 2 classes named Statistics.class and Statistics$1.class
Done.

Note: If you are not using the newest version of RandomSK(2.5 or higher) then it will only work correctly on spigot/bukkit below 1.8 since I stupidly/accidently made the statistics code dependant on versions below 1.8.

**Comment by Mirreski** [comment]
Alternativly you could try this incase you want statistics to work.

Remember to back up the SkQuery4 jar.

Open up SkQuery4 in Winrar. Not SkQuery3.
Go to net/skquery/util/minecraft
Delete the StatisticData.class and StatisticData$1.class
Try starting the server.

Note Untested.
